"""empty message

Revision ID: e6e147c90fd8
Revises: fb23b332a60a
Create Date: 2024-12-06 17:29:54.291263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6e147c90fd8'
down_revision: Union[str, None] = 'fb23b332a60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'type')
    op.drop_column('materials', 'photo')
    op.drop_column('materials', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('materials', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('materials', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
