"""empty message

Revision ID: f9255fcf65fe
Revises: e6e147c90fd8
Create Date: 2024-12-06 17:36:46.182768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9255fcf65fe'
down_revision: Union[str, None] = 'e6e147c90fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('materials_type', sa.String(), nullable=False))
    op.add_column('materials', sa.Column('description', sa.String(), nullable=False))
    op.add_column('materials', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'photo')
    op.drop_column('materials', 'description')
    op.drop_column('materials', 'materials_type')
    # ### end Alembic commands ###
